import type { Metadata } from "next";
import "./globals.css";

import { KoHo } from "next/font/google";

const kohos = KoHo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kohos",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${kohos.variable}`}>
      <body>{children}</body>
    </html>
  );
}
